[files]
extend-exclude = [
"go.mod",
  "go.sum",
  "db",
  "internal/ent/generated/**",
  "internal/ent/historygenerated",
  "internal/testutils/",
  "internal/graphapi/tools_test.go",
  "internal/httpserve/handlers/tools_test.go",
  "internal/graphapi/_example_test.go",
  "internal/httpserve/specs/",
  "internal/graphapi/schema/*",
  "internal/graphapi/historyschema/*",
  "internal/graphapi/model/*",
  "internal/graphapi/generated/*",
  "internal/graphapi/historygenerated/*",
  "internal/graphapi/clientschema/*",
  "internal/graphapi/historyschema/*",
  "internal/graphapi/testclient/*",
  "pkg/catalog/catalog.yaml",
  "pkg/catalog/gencatalog/*",
  ".buildkite/*",
  ".task/*",
  "common/openapi/",
  "plans.yaml",
]
ignore-hidden = true
ignore-files = true
ignore-dot = true
ignore-vcs = true
ignore-global = true
ignore-parent = true

[default]
binary = false
check-filename = true
check-file = true
unicode = true
ignore-hex = true
identifier-leading-digits = false
locale = "en"
extend-ignore-identifiers-re = []
extend-ignore-words-re = [
  "(?i)requestor",
  "(?i)indentity",
  "(?i)encrypter",
  "(?i)seeked",
  "(?i)generater",
  "(?i)policys",
  "typ",
  "vulnerabilitys",
  "(?i)entitys",
  "eis",
]
extend-ignore-re = ["(?Rm)^.*//\\s*spellchecker:disable-line$"]
