{{- if .Values.externalSecrets.enabled }}
{{- range $secretName, $config := .Values.externalSecrets.secrets }}
{{- if $config.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}-ext
  namespace: {{ $.Release.Namespace }}
spec:
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ $secretName }}
    creationPolicy: Owner
  data:
  - secretKey: {{ $config.secretKey }}
    remoteRef:
      key: {{ $config.remoteKey }}
{{- end }}
{{- end }}
{{- end }}
