version: 2
project_name: openlane
builds:
  # ------------------------
  # Darwin amd64
  # ------------------------
  - id: darwin-amd64
    main: ./cmd/cli
    binary: openlane
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - "-X main.Version={{ .Env.VERSION }}"
      - "-X main.Commit={{ .Env.COMMIT }}"
      - "-X main.CommitDate={{ .Env.COMMIT_DATE }}"
      - "-X main.TreeState={{ .Env.TREE_STATE }}"
      - "-X github.com/theopenlane/core/internal/constants.CLIVersion={{ .Env.VERSION }}"

  # ------------------------
  # Darwin arm64
  # ------------------------
  - id: darwin-arm64
    main: ./cmd/cli
    binary: openlane
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - "-X main.Version={{ .Env.VERSION }}"
      - "-X main.Commit={{ .Env.COMMIT }}"
      - "-X main.CommitDate={{ .Env.COMMIT_DATE }}"
      - "-X main.TreeState={{ .Env.TREE_STATE }}"
      - "-X github.com/theopenlane/core/internal/constants.CLIVersion={{ .Env.VERSION }}"
archives:
  - formats: ['tar.gz'] # we can use binary, but it seems there's an issue where goreleaser skips the sboms
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ['zip']
source:
  enabled: true
changelog:
  sort: asc
  use: github
sboms:
  - artifacts: archive
release:
  prerelease: auto
  github:
    owner: theopenlane
    name: core
# This section defines how and which artifacts we want to sign for the release.
signs:
  - cmd: cosign
    args:
      - "sign-blob"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes" # needed on cosign >= 2.0.0
    artifacts: archive
    output: true
